version: "3.9"

services:
    redis:
        image: redis:7-alpine
        container_name: redis
        restart: unless-stopped
        ports:
            - "6379:6379"

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        restart: unless-stopped
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        restart: unless-stopped
        ports:
            - "3000:3000"

    backend:
        build: ./backend
        restart: unless-stopped
        ports:
            - "8000:8000"
        depends_on:
            - redis
        env_file:
            - ./.env

    worker:
        build: ./worker
        ports:
            - "8001:8001"
        depends_on:
            - redis
        env_file:
            - ./.env
